# apparmor.d - Full set of apparmor profiles
# Copyright (c) 2021-2023 Alexandre Pujol <alexandre@pujol.io>
# SPDX-License-Identifier: GPL-2.0-only

# Project information
site_name: AppArmor.d
site_url: https://apparmord.pujol.io
site_author: Alexandre Pujol
site_description: >-
  Full set of AppArmor profiles

# Repository
repo_name: roddhjav/apparmor.d
repo_url: https://github.com/roddhjav/apparmor.d
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2021-2023 Alexandre Pujol

# Configuration
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/file-eye-outline
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/roddhjav
    - icon: fontawesome/brands/github
      link: https://github.com/roddhjav/apparmor.d
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/roddhjav/apparmor.d
    - icon: fontawesome/solid/up-right-from-square
      link: https://pujol.io

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home:
    - index.md
    - Getting Started:
      - concepts.md
      - install.md
      - configuration.md
      - usage.md
    - Advanced:
      - variables.md
      - enforce.md
    - Troubleshooting:
      - issues.md
      - report.md
      - recovery.md
  - Development:
    - development/index.md
    - Architecture:
      - development/guidelines.md
      - development/structure.md
    - Tests:
      - development/tests.md
